name: Unit Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  php-tests:
    runs-on: ${{ matrix.os }}
    env:
      COMPOSER_NO_INTERACTION: 1

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php: [ '8.1', '8.0', '7.4' ]
        hyperf: [ '^2.0' ]
        dependency-version: [prefer-lowest, prefer-stable]
      fail-fast: false

    name: PHP${{ matrix.php }} - Hyperf${{ matrix.hyperf }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: swoole-4.7.1
          ini-values: swoole.use_shortname=Off
          tools: composer:v2

      - name: Install dependencies
        run: |
          composer require "hyperf/contract:${{ matrix.hyperf }}" --no-interaction --no-update
          composer require "hyperf/di:${{ matrix.hyperf }}" --no-interaction --no-update
          composer require "hyperf/command:${{ matrix.hyperf }}" --no-interaction --no-update
          composer require "hyperf/database:${{ matrix.hyperf }}" --no-interaction --no-update --dev
          composer require "hyperf/testing:${{ matrix.hyperf }}" --no-interaction --no-update --dev
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-progress

      - name: Run Test Cases
        run: composer test
